---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.2.4
    hooks:
      - id: rumdl
      - id: rumdl-fmt
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args: [-a, "200,206,403,429", -c, "mlc_config.json"]
