---
name: link-check
on:  # yamllint disable-line rule:truthy
  # Schedule check each day at 8 UTC
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'cook/**/*.cook'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    name: Link Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: '0'

      - name: Get changed files
        id: changed-files
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: tj-actions/changed-files@v45
        with:
          files: |
            docs/**/*.md

      - name: Check markdown links
        uses: lycheeverse/lychee-action@v2
        if: >-
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' ||
          steps.changed-files.outputs.any_changed == 'true'
        with:
          args: >-
            ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
                && 'docs/'
                || steps.changed-files.outputs.all_modified_files }}
          fail: false
